apiVersion: v1
kind: Pod
metadata:
  name: react-app
spec:
  containers:
  - name: react-app
    image: peterjohnson1000/react-test-app:1.0
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 5
